services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  activity-service:
    image: activity-service
    build:
      context: ActivityService/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=12345;Database=activities
    ports:
      - "5102:80"
    depends_on:
      - postgres
      
  gateway-service:
    image: gateway-service
    build:
      context: GatewayService/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5082:80"

volumes:
  pgdata: